@startuml

participant "MochiKernel"             as kernel
box "msh"
    participant "メイン"               as main
    participant "ターミナル\n管理"     as termmng
    participant "コマンドライン\n制御" as clctrl
end box

activate kernel
kernel ->> main: 起動
deactivate kernel
activate main

main -> termmng: 初期化
activate termmng
ref over termmng: 初期化
main <-- termmng:
deactivate termmng

main -> clctrl: 初期化
activate clctrl
ref over clctrl: 初期化
main <-- clctrl:
deactivate clctrl

group 制御開始
    ||5||
    ref over main: メインループ
end group

@enduml
